### ISSUE TITLE
Samenvatting op einde van spel

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#130]
Alle vragen en winnaars tonen in ovezicht

**Comment by Nuytemans-Dieter** [comment]
Database and GroupData should support a list of all questions with top three users of each question

**Comment by Nuytemans-Dieter** [comment]
Database and GroupData support have been implemented for a full question history of the group (see 5354d163aee28f9a5ee212be26da6b118472f266).
No extra actions are required to save the question history, this happens automatically between switching questions.
The history of type `Map<String, Map<String, int>>` can be retreived by `GroupData.getHistory()`, this will never return null. Each String in the outer map is a question (NOT an ID, the question String itself) and each Map contains the userNAME and amount of votes they got.

**Comment by TNelen** [comment]
@Nuytemans-Dieter, pls add bool in groupdata indicating when game is ended, see also #131

**Comment by Nuytemans-Dieter** [comment]
> @Nuytemans-Dieter, pls add bool in groupdata indicating when game is ended, see also #131

This bool has been implemented in GroupData and the database.
It can be retreived by `GroupData#getIsPlaying()` and will be true when the game is still being played. Otherwise, false will be returned. It can be set too, using `GroupData#setIsPlaying( bool )`. Only the admin has access to setting this variable. For non-admins, this method will fail silently.

**Comment by TNelen** [comment]
See OverviewScreen. Thsi can be accessed via ResultsScreen when game has ended.

The same sorting method for the map is used. Added new option in getUserRankingList('overview')
