### ISSUE TITLE
Als je vragen instuurd, assign to category

### ISSUE THREAD

**Issue by TNelen** [TNelen/BlackBox#135]

**Comment by Nuytemans-Dieter** [comment]
Zodat je een categorie moet kiezen als je zelf een vraag instuurt?

**Comment by TNelen** [comment]
> Zodat je een categorie moet kiezen als je zelf een vraag instuurt

Yes exactly. But this matter needs further brainstorming. Since this may override categories with only official questions in the future. 

Placing this issue in the suggestions for now

**Comment by Nuytemans-Dieter** [comment]
> > Zodat je een categorie moet kiezen als je zelf een vraag instuurt
> 
> Yes exactly. But this matter needs further brainstorming. Since this may override categories with only official questions in the future.
> 
> Placing this issue in the suggestions for now

We could add subcategories that in essence are just like any other category as they exist currently, but are named differently (eg. add `[Community]` or `community.` in front of each community category name so that they are unique in the database and so that the difference can be determined by code, in the latter we could also add `official.` in front of official categories). 
A seperate option could be to completely split official and community questions by giving them each their own collection in the database.
